config/routes.rb
Shortstuff::Application.routes.draw do
  resources :short_urls, only: [:new, :create, :show]
  root to: "short_urls#new"

  match '/:name' => 'short_urls#show'
end

app/models/name_generator.rb
class NameGenerator
  def self.generate
    SecureRandom.hex(3)
  end
end

app/models/short_url.rb
class ShortUrl
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations
  attr_reader :url, :name

  validate :name_must_be_unique
  validates :url, format: { with: (/^http(s)?:\/\//), message: "must start with http(s)://" }

  def initialize(options = {})
    if options[:name].present?
      @name = options[:name]
    else
      @name = generate_random_name
    end

    @url = options[:url]
  end

  def save
    if valid?
      create_entry
    end
  end

  def self.find_by_name(name)
    stored_url = redis.get(name)
    if stored_url
      ShortUrl.new(name: name, url: stored_url)
    end
  end

  def full_url
    "http://#{HOSTNAME}/#{name}"
  end

  def as_json(options = {})
    { full_url: full_url }.merge(super)
  end

  private

  def name_must_be_unique
    if existing_entry_with_same_name?
      errors.add(:name, "a link already exists named #{name}")
    end
  end

  def persisted?
    false
  end

  def existing_entry_with_same_name?
    entry_exists_with_name?(@name)
  end

  def entry_exists_with_name?(name)
    redis.exists(name)
  end

  def create_entry
    redis.set(@name, @url)
  end

  def generate_random_name
    name = NameGenerator.generate

    while entry_exists_with_name?(name)
      name = NameGenerator.generate
    end

    name
  end

  def redis
    if ENV['REDIS_PASSWORD']
      @redis ||= Redis.new(:driver => :hiredis, :host => ENV['OPENSHIFT_REDIS_HOST'], :port => ENV['OPENSHIFT_REDIS_PORT'], :password => ENV['REDIS_PASSWORD'])
    else
      @redis ||= Redis.new(:driver => :hiredis)
    end
  end

  def self.redis
    if ENV['REDIS_PASSWORD']
      @redis ||= Redis.new(:driver => :hiredis, :host => ENV['OPENSHIFT_REDIS_HOST'], :port => ENV['OPENSHIFT_REDIS_PORT'], :password => ENV['REDIS_PASSWORD'])
    else
      @redis ||= Redis.new(:driver => :hiredis)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  respond_to :json, :html

  def new
  end

  def create
    short_url = ShortUrl.new(url: params[:url], name: params[:name])
    if short_url.save
      flash[:notice] = "Your url: #{short_url.full_url}"
      respond_to do |format|
        format.html { redirect_to new_short_url_path }
        format.json { render json: short_url.to_json }
      end
    else
      @errors = short_url.errors
      respond_to do |format|
        format.html { render :new }
        format.json { render json: {errors: @errors }, status: :error }
      end
    end

  end

  def show
    short_url = ShortUrl.find_by_name(params[:name])
    if short_url
      redirect_to short_url.url
    else
      flash[:notice] = "This link does not exist."
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <title><%= page_title %></title>
  <%= stylesheet_link_tag :application, :media => 'all' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <header>
  </header>
  <%= render 'flashes' -%>
  <%= yield %>
  <%= render 'javascript' %>
</body>
</html>

app/views/short_urls/new.html.erb
<% if @errors %>
<ul>
  <% @errors.each do |attribute, error|%>
    <li><%= attribute %> - <%= error %></li>
  <% end %>
</ul>
<% end %>
<%= form_tag short_urls_path do |form| %>
  <%= label_tag :url %>
  <%= text_field_tag :url %>
  <%= label_tag :name %>
  <%= text_field_tag :name %>
  <%= submit_tag 'Create'%>
<% end %>